formy/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

formy/post/urls.py
from django.urls import path

from . import views

app_name = 'post'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('<int:pk>', views.detail, name='detail'),
    path('upvote/<int:pk>', views.upvote_post, name='upvote_post'),
    path('downvote/<int:pk>', views.downvote_post, name='downvote_post'),
    path('upvote/comment/<int:postid>/<int:commentid>/', views.upvote_comment, name='upvote_comment'),
    path('downvote/comment/<int:postid>/<int:commentid>/', views.downvote_comment, name='downvote_comment'),

]

formy/post/models.py
from django.db import models

class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=255)
    context = models.TextField()
    views = models.IntegerField(default=0)
    upvote = models.ManyToManyField('accounts.CustomUser', symmetrical=False, related_name='upvoted_posts')
    downvote = models.ManyToManyField('accounts.CustomUser', symmetrical=False, related_name='downvoted_posts')
    posted_by = models.ForeignKey('accounts.CustomUser', related_name='all_posts', on_delete=models.CASCADE)
    posted_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)

    class Meta:
        ordering = ('posted_at', 'title', 'views',)

    def __str__(self):
        return self.title

class Comment(models.Model):
    context = models.TextField()
    upvotes = models.ManyToManyField('accounts.CustomUser', symmetrical=False, related_name='upvoted_comments')
    downvotes = models.ManyToManyField('accounts.CustomUser', symmetrical=False, related_name='downvoted_comments')
    score = models.IntegerField(default=0)
    posted_by = models.ForeignKey('accounts.CustomUser', related_name='user_comments', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='all_comments', on_delete=models.CASCADE)

    class Meta:
        ordering = ('context',)
    
    def __str__(self):
        return self.context
    
    def save(self, *args, **kwargs):
        if self.id:
            self.score = self.upvotes.count() - self.downvotes.count()
        super().save(*args, **kwargs)

formy/post/forms.py
from django import forms

from .models import Post, Comment

INPUT_CLASS = 'w-full mb-4 p-2 border border-solid border-2 border-gray-100 outline-green-400 text-lg rounded-md'

class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'context', 'tags',)


    title = forms.CharField(widget=forms.TextInput(attrs={
        'class': INPUT_CLASS,
        'id': 'titleInput',
        'placeholder': 'Post title'
    }))
    context = forms.CharField(widget=forms.Textarea(attrs={
        'class': INPUT_CLASS,
        'placeholder': 'Post Context'
    }))
    tags = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'hidden',
        'id': 'hiddenfield'
    }))

class NewComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('context',)

    context = forms.CharField(widget=forms.Textarea(attrs={
        'class': INPUT_CLASS,
        'placeholder': 'Your comment',
    }))

formy/post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
import json

from .forms import NewPostForm, NewComment
from .models import Post, Tag, Comment

@login_required
def upvote_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post in request.user.upvoted_posts.all():
        post.upvote.remove(request.user)
    else:
        if post in request.user.downvoted_posts.all():
            post.downvote.remove(request.user)
        post.upvote.add(request.user)

    return redirect('post:detail', pk)

@login_required
def downvote_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post in request.user.downvoted_posts.all():
        post.downvote.remove(request.user)
    else:
        if post in request.user.upvoted_posts.all():
            post.upvote.remove(request.user)
        post.downvote.add(request.user)

    return redirect('post:detail', pk)

@login_required
def upvote_comment(request, postid, commentid):
    comment = get_object_or_404(Comment, pk=commentid)
    if comment in request.user.upvoted_comments.all():
        comment.upvotes.remove(request.user)
    else:
        if comment in request.user.downvoted_comments.all():
            comment.downvotes.remove(request.user)
        comment.upvotes.add(request.user)
    comment.save()

    return redirect('post:detail', postid)  

@login_required
def downvote_comment(request, postid, commentid):
    comment = get_object_or_404(Comment, pk=commentid)
    if comment in request.user.downvoted_comments.all():
        comment.downvotes.remove(request.user)
    else:
        if comment in request.user.upvoted_comments.all():
            comment.upvotes.remove(request.user)
        comment.downvotes.add(request.user)
    comment.save()

    return redirect('post:detail', postid)

def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.views += 1
    post.save()
    score = post.upvote.count() - post.downvote.count()

    if request.method == 'POST':
        form = NewComment(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.posted_by = request.user
            comment.post = post
            comment.save()

            return redirect('post:detail', pk)
    else:
        form = NewComment()

    return render(request, 'post/detail.html', {
        'post': post,
        'score': score,
        'form': form,
    })

@login_required
def new(request):
    if request.method == 'POST':
        print(request.POST['tags'])
        form = NewPostForm(request.POST)
        tags = json.loads(request.POST['tags'])['tags']
        tagsModels = []
        for tag in tags:
            tag = Tag.objects.get_or_create(name=tag)[0]
            tagsModels.append(tag)
            print("in for")
        if form.is_valid():
            print("form is valid`")
            form.instance.posted_by = request.user
            instance = form.save(commit=False)
            instance.save()
            instance.tags.set(tagsModels)
            return redirect('/')
    else:
        form = NewPostForm()

    return render(request, 'post/new.html', {
        'form': form
    })

formy/post/templates/post/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block editorLink %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}

{% block content %}
<div class="w-full h-full p-4 flex gap-10">
    {% include 'core/sidebar.html' %}
    <div class="px-4 py-6 w-full h-full">
        <div class="mb-4 head border-b-2 border-stone-300">
            <h1 class="mb-4 text-3xl font-bold text-stone-800">{{ post.title }}</h1>
            <div class="flex align-center text-stone-600">
                <a href="#" class="inline-block mr-4">{{ post.posted_by }}</a>
                <div class="mb-2 mr-4">Views: {{ post.views }}</div>
                <div class="mb-2 mr-4">Asked at: {{ post.posted_at }}</div>
                {% if post.posted_at != post.modified_at %}
                    <div class="mb-2">Modified at:{{ post.modified_at }}</div>
                {% endif %}
            </div>
        </div>
        <div class="main grid grid-cols-[auto_1fr] gap-4">
            <div class="updown grid justify-items-center grid-rows-[min-content_min-content_min-content] text-stone-800">
                <a href="{% url 'post:upvote_post' post.id %}" class="inline-block text-5xl"><i class="fa-solid fa-fw fa-caret-up"></i></a>
                <div class="text-xl font-bold">{{ score }}</div>
                <a href="{% url 'post:downvote_post' post.id %}" class="inline-block text-5xl"><i class="fa-solid fa-fw fa-caret-down"></i></a>
            </div>
            <div class="content">
                <div class="parse mb-6 text-stone-800" data-content="{{ post.context }}">{{ post.context }}</div>
                <div class="">
                    <div class="">
                        {% for tag in post.tags.all %}
                            <a href="#" class="px-2 py-1 inline-block text-sm bg-green-100 rounded-md">{{ tag }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="comments">
            {% for comment in post.all_comments.all %}
            <div class="main grid grid-cols-[auto_1fr] gap-4 border-t-2">
                <div class="updown grid justify-items-center grid-rows-[min-content_min-content_min-content] text-stone-800">
                    <a href="{% url 'post:upvote_comment' post.id comment.id %}" class="inline-block text-5xl"><i class="fa-solid fa-fw fa-caret-up"></i></a>
                    <div class="text-xl font-bold">{{ comment.score }}</div>
                    <a href="{% url 'post:downvote_comment' post.id comment.id %}" class="inline-block text-5xl"><i class="fa-solid fa-fw fa-caret-down"></i></a>
                </div>
                <div class="content">
                    <div class="parse mb-6 text-stone-800" data-content="{{ comment.context }}">{{ comment.context }}</div>
                </div>
            </div>
            <div class="main grid grid-cols-[auto_1fr] gap-4 border-t-2">
                <div class="updown grid justify-items-center text-stone-800">
                    <a href="{% url 'post:upvote_comment' post.id comment.id %}" class="inline-block text-5xl"><i class="fa-solid fa-fw fa-caret-up"></i></a>
                    <div class="text-xl font-bold">1</div>
                    <a href="{% url 'post:downvote_comment' post.id comment.id %}" class="inline-block text-5xl"><i class="fa-solid fa-fw fa-caret-down"></i></a>
                </div>
                <div class="content">
                    <div class="parse mb-6 text-stone-800" data-content="{{ comment.context }}"># Hello\n\n** this is my first markdown comment here **</div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% if request.user.is_authenticated %}
        <form>
            {% csrf_token %}
            <div class="mb-3">
                <textarea name="context" id="textEditor"></textarea>
            </div>
            <button type="button" id="submitBtn" class="w-full bg-green-400 text-2xl p-2 font-medium text-white rounded-md">Send</button>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block editorScript %}
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
{% endblock %}
{% block markedjs %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/12.0.0/marked.min.js" integrity="sha512-tjg8I2d6Fi0OBGz1csmr7RfI4uupYaCfL/RqhVRTS42RMGwfBsjwBGmhzhI+e2dPmyew8cFkoxnVkGvADDLvbg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}
{% block script %}
    {% load static %}
    <script src="{% static 'post/detail.js' %}"></script>
{% endblock %}

formy/post/templates/post/new.html
{% extends 'core/base.html' %}

{% block title %}New Post{% endblock %}

{% block editorLink %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}

{% block content %}
<div class="px-4 py-6 w-full h-full text-stone-800">
    <h1 class="font-bold text-3xl">New Post</h1>

    <form>
        {% csrf_token %}

        <div class="mb-3">
            <label for="title">Title:</label>
            {{ form.title }}
        </div>

        <div class="mb-3">
            <label>Context:</label>
            <textarea name="context" id="contextEditor"></textarea>
        </div>

        <div class="w-full flex flex-wrap items-center px-2 mb-4 border border-solid border-2 border-gray-100 outline-green-400 text-lg rounded-md hover:border-green-400">
            <span id="tagContainer" class="flex flex-wrap items-center gap-2"></span>
            <input type="text" id="tagInput" class="grow p-2 outline-none" />
            <input name="tags" id="hiddenfield" class="hidden"/>
        </div>

        <button type="button" id="submitBtn" class="w-full p-2 font-bold text-lg rounded-md bg-green-500 hover:bg-green-600 text-white">Create</button>
    </form>
</div>
{% endblock %}

{% block editorScript %}
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
{% endblock %}
{% block script %}
    {% load static %}
    <script src="{% static 'post/new_post.js' %}"></script>
{% endblock %}