formy/accounts/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path('', views.profile, name='profile'),
]

formy/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

formy/post/urls.py
from django.urls import path

from . import views

app_name = 'post'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('<int:pk>', views.detail, name='detail'),
    path('upvote/<int:pk>', views.upvote_post, name='upvote_post'),
    path('downvote/<int:pk>', views.downvote_post, name='downvote_post'),
    path('upvote/comment/<int:postid>/<int:commentid>/', views.upvote_comment, name='upvote_comment'),
    path('downvote/comment/<int:postid>/<int:commentid>/', views.downvote_comment, name='downvote_comment'),

]

formy/core/models.py
from django.db import models

# Create your models here.

formy/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from accounts.forms import CustomUserCreationForm, CustomUserChangeForm
from accounts.models import CustomUser

class SignupForm(CustomUserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2',)

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'w-full border border-solid border-2 border-gray-200 outline-green-400 mb-4',
        'placeholder': 'You username'
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'w-full border border-solid border-2 border-gray-200 outline-green-400 mb-4',
        'placeholder': 'You email'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full border border-solid border-2 border-gray-200 outline-green-400 mb-4',
        'placeholder': 'You password'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full border border-solid border-2 border-gray-200 outline-green-400 mb-4',
        'placeholder': 'Reenter password'
    }))


class LoginForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password',)
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'w-full border border-solid border-2 border-gray-200 outline-green-400 mb-4',
        'placeholder': 'You username'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full border border-solid border-2 border-gray-200 outline-green-400 mb-4',
        'placeholder': 'You password'
    }))

formy/core/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .forms import SignupForm, LoginForm
from accounts.models import CustomUser
from post.models import Post

def index(request):
    posts = Post.objects.all()
    # tags = get_object_or_404(Post, id=19).tags.all()
    # print(tags)
    # posts = Post.objects.filter(id=17)

    return render(request, 'core/index.html', {
        'posts': posts,
    })


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

formy/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | Formy</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    {% block editorLink %}{% endblock %}
	{% block stylesheet %}{% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.tailwindcss.com"></script>
    <style type="text/tailwindcss">
        @layer base {
          h1 {
            @apply text-3xl
          }
          h2 {
            @apply text-2xl
          }
          h3 {
            @apply text-xl
          }
          h4 {
            @apply text-lg
          }
          h5 {
            @apply text-base
          }
          h6 {
            @apply text-sm
          }
        }
      </style>
</head>
<body class="h-screen grid grid-rows-[auto,1fr,auto]">
    <nav class="w-full p-4 self-start flex justify-between align-center shadow-sm">
        <a href="/" class="inline-block text-4xl font-bold text-green-400 transition-colors hover:text-stone-800">Formy</a>
        <ul class="flex align-center items-center">
            <li><a href="/" class="font-medium text-xl transition-colors hover:text-green-500 mr-6">Home</a></li>
            <li><a href="#" class="font-medium text-xl transition-colors hover:text-green-500 mr-6">Topics</a></li>
            {% if request.user.is_authenticated %}
            <!-- <li><a href="#" class="font-medium text-xl transition-colors hover:text-green-500 mr-6"><i class="fa-regular fa-message text-4xl"></i></a></li> -->
            <li><a href="{% url 'post:new' %}" class="font-medium text-xl transition-colors hover:text-green-500 mr-6">+ New Post</a></li>
            <li id="profile" class="relative"><a href="#" class="inline-block font-medium transition-colors hover:text-green-500 flex justify-center align-centers rounded-full w-12 h-12 border border-4 border-solid border-stone-800 hover:border-green-500 p-2"><i class="fa-solid fa-user text-xl"></i></a>
                <ul id="profileContext" class="hidden w-40 mt-2 bg-white absolute right-0 shadow-md rounded-sm border">
                    <li><a href="{% url 'user:profile' %}" class="block hover:bg-gray-100 py-2 pl-2 pr-6">User Profile</a></li>
                    <li><a href="#" class="block hover:bg-gray-100 py-2 pl-2 pr-6">Settings</a></li>
                    <li><a href="#" class="block hover:bg-gray-100 py-2 pl-2 pr-6">Posts</a></li>
                </ul>
            </li>
            {% else %}
            <li><a href="{% url 'core:login' %}" class="mr-4 font-medium text-xl py-2 px-4 border border-solid border-2 border-green-500 transition-colors hover:text-white hover:bg-green-500 rounded-lg">Login</a></li>
            <li><a href="{% url 'core:signup' %}" class="font-medium text-xl py-2 px-4 border border-solid border-2 border-green-500 transition-colors text-white hover:text-stone-800 bg-green-500 hover:bg-white rounded-lg">Sign up</a></li>
            {% endif %}
        </ul>
    </nav>
    <div class="w-full grid place-items-center">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="w-full self-end px-4 py-8 bg-green-500 flex gap-14">
        <div class="w-1/3">
            <a href="/" class="inline-block mb-4 text-4xl font-bold text-white">Formy</a>
            <p class="text-white">Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis consequatur dignissimos reprehenderit deleniti, nihil exercitationem?</p>
        </div>
        <div class="w-2/3 text-white flex gap-12">
            <ul class="space-y-2">
                <h3 class="font-bold text-lg">Menu</h3>
                <li><a href="/">Home</a></li>
                <li><a href="#">Topics</a></li>
                <li><a href="#">User list</a></li>
                <li><a href="#">Something else</a></li>
            </ul>
            <ul class="space-y-2">
                <h3 class="font-bold text-lg">Details</h3>
                <li><a href="#">Contact</a></li>
                <li><a href="#">Terms of Service</a></li>
                <li><a href="#">Community Rules</a></li>
                <li><a href="#">Privacy Policy</a></li>
            </ul>
        </div>
    </footer>

    {% block editorScript %}{% endblock %}
    {% block markedjs %}{% endblock %}
    {% block script %}{% endblock %}
    {% load static %}
    <script src="{% static 'core/moment.js' %}"></script>
    <script src="{% static 'core/index.js' %}"></script>
</body>
</html>

formy/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
<div class="w-full h-full p-4 flex gap-10">
    {% include 'core/sidebar.html' %}
    <div class="w-full">
        <ul>
            {% for post in posts %}
                <li><a href="{% url 'post:detail' post.id %}">
                    <div class="mb-2 p-2 bg-gray-100 rounded-lg flex justify-between">
                        <div class="">
                            <div class="text-lg">{{ post.title }}</div>
                            <div class="">{{ post.posted_by }}</div>
                        </div>
                        <div class="additionalData">
                            <!-- 
                                Date is initially placed at .postTimeHidden, which will 
                                be processed with moment.js in core/index.js to be shown
                                in .postTime
                             -->
                            <div class="postTime text-sm">loading...</div>
                            <div class="postTimeHidden hidden">{{ post.posted_at }}</div>
                        </div>
                    </div>
                </a></li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

formy/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="p-4 shadow-md hover:shadow-green-200 border border-2 border-solid border-gray-200 rounded-md transition-colors hover:border-green-500">
    <h1 class="text-4xl font-bold mb-4">Login</h1>
    <form method="POST" action="">
        {% csrf_token %}

        {{ form.as_p }}
        <button type="submit" class="w-full mt-6 bg-green-400 p-2 text-xl text-white font-bold rounded-md">Login</button>
    </form>
</div>
{% endblock %}

formy/core/templates/core/sidebar.html
<div class="py-2 border-r-2">
    <ul>
        <li><a href="#" class="flex py-1 px-2 pr-8 items-center gap-2 rounded-l-md text-lg hover:bg-green-200"><i class="fa-solid fa-fw fa-house"></i> Home</a></li>
        <li><a href="#" class="flex py-1 px-2 pr-8 items-center gap-2 rounded-l-md text-lg hover:bg-green-200"><i class="fa-solid fa-fw fa-tags"></i> Tags</a></li>
    </ul>
</div>

formy/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="p-4 shadow-md hover:shadow-green-200 border border-2 border-solid border-gray-200 rounded-md transition-colors hover:border-green-500">
    <h1 class="text-4xl font-bold">Sign up</h1>
    <form method="POST" action="">
        {% csrf_token %}

        {{ form.as_p }}
    </form>
</div>
{% endblock %}